//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeesApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEmployee
    {
        public int EmployeeID { get; set; }
        public string FullName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string IdCardNumber { get; set; }
        public string JMBG { get; set; }
        public int GenderID { get; set; }
        public string PhoneNumber { get; set; }
        public int SectorID { get; set; }
        public string LocationOfEmployee { get; set; }
        public int Manager { get; set; }
    }
}
